### ISSUE TITLE
+update and nodemon

### ISSUE THREAD

**Issue by sleme** [sleme/pal-bot#5]
Before this problem emerged +update would restart the bot and get updates from here and nodemon would auto restart the app.js now it does not work. It was dodgy before can you have a look into it?

**Comment by julianYaman** [comment]
Use pm2 for real production purpose.

**Comment by sleme** [comment]
Been fixed using pm2 (for the moment)

**Comment by julianYaman** [comment]
Do you still using pm2 or nodemon again?

**Comment by sleme** [comment]
Pm2
